### ISSUE TITLE
jdrivesync ignores -r option and filename

### ISSUE THREAD

**Issue by mfisheresq** [siom79/jdrivesync#22]
I have a local directory "Foxcam_Images" containing a single file: testfile
I have a Drive folder also called "Foxcam_Images"

The following command should upload the file to the remote folder. It does upload the file, but it is uploaded as a file called "Untitled" in my Drive's root directory.

java -jar jdrivesync-0.4.0-jar-with-dependencies.jar -u --no-delete -l Foxcam_Images -r Foxcam_Images

**Comment by siom79** [comment]
The URL for resumable uploads was not upgraded to the v3 API. This did not cause an error message but led silently to the wrong result meaning that the parent folder was ignored.

This is fixed in the version 0.4.1 that you can download [here](https://github.com/siom79/jdrivesync/releases/tag/jdrivesync-0.4.1).

Thanks for reporting.
